# Read html data

In [11]:
import pandas as pd

In [13]:
nba = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2020_per_game.html')

In [14]:
len(nba)

1

In [17]:
nba= nba[0]

In [18]:
nba.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Steven Adams,C,26,OKC,60,60,27.1,4.5,7.7,...,.589,3.4,6.0,9.4,2.4,0.8,1.1,1.5,2.0,11.0
1,2,Bam Adebayo,PF,22,MIA,67,67,34.2,6.3,11.0,...,.693,2.5,7.9,10.4,5.1,1.2,1.3,2.9,2.5,16.2
2,3,LaMarcus Aldridge,C,34,SAS,53,53,33.1,7.4,15.0,...,.827,1.9,5.5,7.4,2.4,0.7,1.6,1.4,2.4,18.9
3,4,Nickeil Alexander-Walker,SG,21,NOP,43,0,12.0,1.9,5.4,...,.600,0.2,1.7,1.9,1.8,0.3,0.2,0.9,1.2,5.3
4,5,Grayson Allen,SG,24,MEM,33,0,17.5,2.8,6.0,...,.846,0.2,2.0,2.2,1.4,0.3,0.0,0.8,1.3,7.8

In [19]:
import requests

In [20]:
html_url ="https://en.wikipedia.org/wiki/The_Simpsons"

In [22]:
r= requests.get(html_url)

In [23]:
wiki_tables= pd.read_html(r.text, header=0)

In [24]:
len(wiki_tables)

27

In [25]:
simpsons= wiki_tables[1]

In [26]:
simpsons.head()

,Season,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
0,Season,Season,No. ofepisodes,Season premiere,Season finale,Time Slot (ET),Avg. viewers(in millions),Most watched episode,Most watched episode
1,Season,Season,No. ofepisodes,Season premiere,Season finale,Time Slot (ET),Avg. viewers(in millions),Viewers(millions),Episode Title
2,1,1989â€“90,13,"December 17, 1989","May 13, 1990",Sunday 8:30Â pm,27.8,33.5,"""Life on the Fast Lane"""
3,2,1990â€“91,22,"October 11, 1990","July 11, 1991",Thursday 8:00Â pm,24.4,33.6,"""Bart Gets an F"""
4,3,1991â€“92,24,"September 19, 1991","August 27, 1992",Thursday 8:00Â pm,21.8,25.5,"""Colonel Homer"""

In [27]:
simpsons.drop([0, 1], inplace= True)

In [29]:
simpsons.set_index('Season', inplace= True)

In [31]:
simpsons['No. ofepisodes'].unique()

array(['13', '22', '24', '25', '23', '21', '20', 'TBA'], dtype=object)

In [32]:
simpsons= simpsons.loc[simpsons['No. ofepisodes']!= 'TBA']

In [33]:
simpsons

,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989â€“90,13,"December 17, 1989","May 13, 1990",Sunday 8:30Â pm,27.8,33.5,"""Life on the Fast Lane"""
2,1990â€“91,22,"October 11, 1990","July 11, 1991",Thursday 8:00Â pm,24.4,33.6,"""Bart Gets an F"""
3,1991â€“92,24,"September 19, 1991","August 27, 1992",Thursday 8:00Â pm,21.8,25.5,"""Colonel Homer"""
4,1992â€“93,22,"September 24, 1992","May 13, 1993",Thursday 8:00Â pm,22.4,28.6,"""Lisa's First Word"""
5,1993â€“94,22,"September 30, 1993","May 19, 1994",Thursday 8:00Â pm,18.9,24.0,"""Treehouse of Horror IV"""
6,1994â€“95,25,"September 4, 1994","May 21, 1995",Sunday 8:00Â pm,15.6,22.2,"""Treehouse of Horror V"""
7,1995â€“96,25,"September 17, 1995","May 19, 1996",Sunday 8:00Â pm,15.1,19.7,"""Treehouse of Horror VI"""
8,1996â€“97,25,"October 27, 1996","May 18, 1997",Sunday 8:30Â pm (Episodes 1â€“3)Sunday 8:00Â pm (E...,14.5,20.9,"""The Springfield Files"""
9,1997â€“98,25,"September 21, 1997","May 17, 1998",Sunday 8:00Â pm,15.3,19.8,"""The Two Mrs. Nahasapeemapetilons"""
10,1998â€“99,23,"August 23, 1998","May 16, 1999",Sunday 8:00Â pm,13.5,15.5,"""Maximum Homerdrive"""
11,1999â€“2000,22,"September 26, 1999","May 21, 2000",Sunday 8:00Â pm,8.8,18.4,"""The Mansion Family"""
12,2000â€“01,21,"November 1, 2000","May 20, 2001",Sunday 8:00Â pm,15.5,18.6,"""Worst Episode Ever"""
13,2001â€“02,22,"November 6, 2001","May 22, 2002",Tuesday 8:30Â pm (Episode 1)Sunday 8:00Â pm (Epi...,12.5,14.9,"""The Parent Rap"""
14,2002â€“03,22,"November 3, 2002","May 18, 2003","Sunday 8:00Â pm (Episodes 1â€“11, 13â€“21)Sunday 8:...",14.4,22.1,"""I'm Spelling as Fast as I Can"""
15,2003â€“04,22,"November 2, 2003","May 23, 2004",Sunday 8:00Â pm,11.0,16.3,"""I, (Annoyed Grunt)-Bot"""
16,2004â€“05,21,"November 7, 2004","May 15, 2005","Sunday 8:00Â pm (Episodes 1â€“7, 9â€“16, 18, 20)Sun...",10.2,23.07,"""Homer and Ned's Hail Mary Pass"""
17,2005â€“06,22,"September 11, 2005","May 21, 2006",Sunday 8:00Â pm,9.55,11.63,"""Treehouse of Horror XVI"""
18,2006â€“07,22,"September 10, 2006","May 20, 2007",Sunday 8:00Â pm,9.15,13.90,"""The Wife Aquatic"""
19,2007â€“08,20,"September 23, 2007","May 18, 2008",Sunday 8:00Â pm,8.37,11.7,"""Treehouse of Horror XVIII"""
20,2008â€“09,21,"September 28, 2008","May 17, 2009",Sunday 8:00Â pm,7.1,12.4,"""Treehouse of Horror XIX"""
21,2009â€“10,23,"September 27, 2009","May 23, 2010",Sunday 8:00Â pm,7.1,14.62,"""Once Upon a Time in Springfield"""
22,2010â€“11,22,"September 26, 2010","May 22, 2011",Sunday 8:00Â pm,7.09,12.6,"""Moms I'd Like to Forget"""
23,2011â€“12,22,"September 25, 2011","May 20, 2012",Sunday 8:00Â pm,6.15[148],11.48,"""The D'oh-cial Network"""
24,2012â€“13,22,"September 30, 2012","May 19, 2013",Sunday 8:00Â pm,5.41[149],8.97,"""Homer Goes to Prep School"""
25,2013â€“14,22,"September 29, 2013","May 18, 2014",Sunday 8:00Â pm,5.02[150],12.04,"""Steal This Episode"""
26,2014â€“15,22,"September 28, 2014","May 17, 2015",Sunday 8:00Â pm,5.61[151],10.62,"""The Man Who Came to Be Dinner"""
27,2015â€“16,22,"September 27, 2015","May 22, 2016",Sunday 8:00Â pm,4.0[152],8.33,"""Teenage Mutant Milk-Caused Hurdles"""
28,2016â€“17,22,"September 25, 2016","MayÂ 21,Â 2017",Sunday 8:00Â pm,4.80[153],8.19,"""Pork and Burns"""
29,2017â€“18,21,"October 1, 2017","May 20, 2018",Sunday 8:00Â pm,4.07[154],8.04,"""Frink Gets Testy"""
30,2018â€“19,23,"September 30, 2018","May 12, 2019",Sunday 8:00Â pm,3.10[155],8.20,"""The Girl on the Bus"""
31,2019â€“20,22,"September 29, 2019","May 17, 2020",Sunday 8:00Â pm,2.58[156],5.63,"""Go Big or Go Homer"""

In [35]:
min_season= simpsons['No. ofepisodes'].min()

In [36]:
min_season

'13'

In [39]:
simpsons.loc[simpsons['No. ofepisodes']== min_season]

,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989â€“90,13,"December 17, 1989","May 13, 1990",Sunday 8:30Â pm,27.8,33.5,"""Life on the Fast Lane"""

# Read excel files

In [42]:
df= pd.read_excel('SampleData.xlsx')

In [43]:
df.head()

   OrderDate   Region      Rep    Item  Units  Unit Cost   Total
0 2019-01-06     East    Jones  Pencil     95       1.99  189.05
1 2019-01-23  Central   Kivell  Binder     50      19.99  999.50
2 2019-02-09  Central  Jardine  Pencil     36       4.99  179.64
3 2019-02-26  Central     Gill     Pen     27      19.99  539.73
4 2019-03-15     West  Sorvino  Pencil     56       2.99  167.44

In [44]:
df

    OrderDate   Region       Rep     Item  Units  Unit Cost    Total
0  2019-01-06     East     Jones   Pencil     95       1.99   189.05
1  2019-01-23  Central    Kivell   Binder     50      19.99   999.50
2  2019-02-09  Central   Jardine   Pencil     36       4.99   179.64
3  2019-02-26  Central      Gill      Pen     27      19.99   539.73
4  2019-03-15     West   Sorvino   Pencil     56       2.99   167.44
5  2019-04-01     East     Jones   Binder     60       4.99   299.40
6  2019-04-18  Central   Andrews   Pencil     75       1.99   149.25
7  2019-05-05  Central   Jardine   Pencil     90       4.99   449.10
8  2019-05-22     West  Thompson   Pencil     32       1.99    63.68
9  2019-06-08     East     Jones   Binder     60       8.99   539.40
10 2019-06-25  Central    Morgan   Pencil     90       4.99   449.10
11 2019-07-12     East    Howard   Binder     29       1.99    57.71
12 2019-07-29     East    Parent   Binder     81      19.99  1619.19
13 2019-08-15     East     Jones   Pencil     35       4.99   174.65
14 2019-09-01  Central     Smith     Desk      2     125.00   250.00
15 2019-09-18     East     Jones  Pen Set     16      15.99   255.84
16 2019-10-05  Central    Morgan   Binder     28       8.99   251.72
17 2019-10-22     East     Jones      Pen     64       8.99   575.36
18 2019-11-08     East    Parent      Pen     15      19.99   299.85
19 2019-11-25  Central    Kivell  Pen Set     96       4.99   479.04
20 2019-12-12  Central     Smith   Pencil     67       1.29    86.43
21 2019-12-29     East    Parent  Pen Set     74      15.99  1183.26
22 2020-01-15  Central      Gill   Binder     46       8.99   413.54
23 2020-02-01  Central     Smith   Binder     87      15.00  1305.00
24 2020-02-18     East     Jones   Binder      4       4.99    19.96
25 2020-03-07     West   Sorvino   Binder      7      19.99   139.93
26 2020-03-24  Central   Jardine  Pen Set     50       4.99   249.50
27 2020-04-10  Central   Andrews   Pencil     66       1.99   131.34
28 2020-04-27     East    Howard      Pen     96       4.99   479.04
29 2020-05-14  Central      Gill   Pencil     53       1.29    68.37
30 2020-05-31  Central      Gill   Binder     80       8.99   719.20
31 2020-06-17  Central    Kivell     Desk      5     125.00   625.00
32 2020-07-04     East     Jones  Pen Set     62       4.99   309.38
33 2020-07-21  Central    Morgan  Pen Set     55      12.49   686.95
34 2020-08-07  Central    Kivell  Pen Set     42      23.95  1005.90
35 2020-08-24     West   Sorvino     Desk      3     275.00   825.00
36 2020-09-10  Central      Gill   Pencil      7       1.29     9.03
37 2020-09-27     West   Sorvino      Pen     76       1.99   151.24
38 2020-10-14     West  Thompson   Binder     57      19.99  1139.43
39 2020-10-31  Central   Andrews   Pencil     14       1.29    18.06
40 2020-11-17  Central   Jardine   Binder     11       4.99    54.89
41 2020-12-04  Central   Jardine   Binder     94      19.99  1879.06
42 2020-12-21  Central   Andrews   Binder     28       4.99   139.72

In [48]:
df.to_excel('out.xlsx', startrow=1, startcol=2)

In [49]:
pd.read_excel('out.xlsx')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,OrderDate,Region,Rep,Item,Units,Unit Cost,Total
1,NaN,NaN,0.0,2019-01-06 00:00:00,East,Jones,Pencil,95,1.99,189.05
2,NaN,NaN,1.0,2019-01-23 00:00:00,Central,Kivell,Binder,50,19.99,999.5
3,NaN,NaN,2.0,2019-02-09 00:00:00,Central,Jardine,Pencil,36,4.99,179.64
4,NaN,NaN,3.0,2019-02-26 00:00:00,Central,Gill,Pen,27,19.99,539.73
5,NaN,NaN,4.0,2019-03-15 00:00:00,West,Sorvino,Pencil,56,2.99,167.44
6,NaN,NaN,5.0,2019-04-01 00:00:00,East,Jones,Binder,60,4.99,299.4
7,NaN,NaN,6.0,2019-04-18 00:00:00,Central,Andrews,Pencil,75,1.99,149.25
8,NaN,NaN,7.0,2019-05-05 00:00:00,Central,Jardine,Pencil,90,4.99,449.1
9,NaN,NaN,8.0,2019-05-22 00:00:00,West,Thompson,Pencil,32,1.99,63.68
10,NaN,NaN,9.0,2019-06-08 00:00:00,East,Jones,Binder,60,8.99,539.4
11,NaN,NaN,10.0,2019-06-25 00:00:00,Central,Morgan,Pencil,90,4.99,449.1
12,NaN,NaN,11.0,2019-07-12 00:00:00,East,Howard,Binder,29,1.99,57.71
13,NaN,NaN,12.0,2019-07-29 00:00:00,East,Parent,Binder,81,19.99,1619.19
14,NaN,NaN,13.0,2019-08-15 00:00:00,East,Jones,Pencil,35,4.99,174.65
15,NaN,NaN,14.0,2019-09-01 00:00:00,Central,Smith,Desk,2,125,250
16,NaN,NaN,15.0,2019-09-18 00:00:00,East,Jones,Pen Set,16,15.99,255.84
17,NaN,NaN,16.0,2019-10-05 00:00:00,Central,Morgan,Binder,28,8.99,251.72
18,NaN,NaN,17.0,2019-10-22 00:00:00,East,Jones,Pen,64,8.99,575.36
19,NaN,NaN,18.0,2019-11-08 00:00:00,East,Parent,Pen,15,19.99,299.85
20,NaN,NaN,19.0,2019-11-25 00:00:00,Central,Kivell,Pen Set,96,4.99,479.04
21,NaN,NaN,20.0,2019-12-12 00:00:00,Central,Smith,Pencil,67,1.29,86.43
22,NaN,NaN,21.0,2019-12-29 00:00:00,East,Parent,Pen Set,74,15.99,1183.26
23,NaN,NaN,22.0,2020-01-15 00:00:00,Central,Gill,Binder,46,8.99,413.54
24,NaN,NaN,23.0,2020-02-01 00:00:00,Central,Smith,Binder,87,15,1305
25,NaN,NaN,24.0,2020-02-18 00:00:00,East,Jones,Binder,4,4.99,19.96
26,NaN,NaN,25.0,2020-03-07 00:00:00,West,Sorvino,Binder,7,19.99,139.93
27,NaN,NaN,26.0,2020-03-24 00:00:00,Central,Jardine,Pen Set,50,4.99,249.5
28,NaN,NaN,27.0,2020-04-10 00:00:00,Central,Andrews,Pencil,66,1.99,131.34
29,NaN,NaN,28.0,2020-04-27 00:00:00,East,Howard,Pen,96,4.99,479.04
30,NaN,NaN,29.0,2020-05-14 00:00:00,Central,Gill,Pencil,53,1.29,68.37
31,NaN,NaN,30.0,2020-05-31 00:00:00,Central,Gill,Binder,80,8.99,719.2
32,NaN,NaN,31.0,2020-06-17 00:00:00,Central,Kivell,Desk,5,125,625
33,NaN,NaN,32.0,2020-07-04 00:00:00,East,Jones,Pen Set,62,4.99,309.38
34,NaN,NaN,33.0,2020-07-21 00:00:00,Central,Morgan,Pen Set,55,12.49,686.95
35,NaN,NaN,34.0,2020-08-07 00:00:00,Central,Kivell,Pen Set,42,23.95,1005.9
36,NaN,NaN,35.0,2020-08-24 00:00:00,West,Sorvino,Desk,3,275,825
37,NaN,NaN,36.0,2020-09-10 00:00:00,Central,Gill,Pencil,7,1.29,9.03
38,NaN,NaN,37.0,2020-09-27 00:00:00,West,Sorvino,Pen,76,1.99,151.24
39,NaN,NaN,38.0,2020-10-14 00:00:00,West,Thompson,Binder,57,19.99,1139.43
40,NaN,NaN,39.0,2020-10-31 00:00:00,Central,Andrews,Pencil,14,1.29,18.06
41,NaN,NaN,40.0,2020-11-17 00:00:00,Central,Jardine,Binder,11,4.99,54.89
42,NaN,NaN,41.0,2020-12-04 00:00:00,Central,Jardine,Binder,94,19.99,1879.06
43,NaN,NaN,42.0,2020-12-21 00:00:00,Central,Andrews,Binder,28,4.99,139.72